---
- include: packages.yml

- name: Create jasper user
  user: name={{ jasper_user }} comment="jasper" shell=/bin/bash groups=audio append=yes

- name: Clone jasper repo
  git: repo={{ jasper_git_url }} dest={{ jasper_path }} version={{ jasper_git_version }}
  become_user: "{{ jasper_user }}"

- include: cmuclmtk.yml

- include: phonetisaurus.yml

- include: pip.yml

- name: Create settings directory
  file: path={{ jasper_base_path }}/.jasper state=directory
  become_user: "{{ jasper_user }}"

- name: Create settings file
  template: src=profile.yml.j2 dest={{ jasper_base_path }}/.jasper/profile.yml
  become_user: "{{ jasper_user }}"
  notify:
  - Restart jasper

- include: raspberrypi.yml
  when: "'raspberry' in groups and '{{ ansible_hostname }}' in groups['raspberry']"

- name: Install systemd unit
  template: src=jasper.service.j2 dest=/etc/systemd/system/jasper.service

- name: Enable jasper service
  # Manually, see ansible-modules-core #3784
  systemd: enabled=True name=jasper
  notify:
  - Restart jasper
